import type { MarketingProgram } from "@/types/program";

export const marketingPrograms: MarketingProgram[] = [
  {
    slug: "full-stack-development",
    title: "Full Stack Development",
    category: "Engineering",
    eyebrow: "BUILD FOR THE WEB",
    description: "Build, test, and deploy modern web products across the complete stack.",
    about: "This project-led program takes you from web foundations to production deployment. You will build responsive interfaces, secure APIs, relational data models, and a portfolio-ready capstone while learning how professional teams plan, review, and ship software.",
    duration: "6 months",
    level: "Beginner to intermediate",
    students: "22,131",
    rating: "4.9",
    price: "₹15,999",
    modules: "8 modules",
    projects: "6 projects",
    accent: "from-fuchsia-500 via-violet-600 to-indigo-700",
    coverImage: "/images/programs/full-stack-development.webp",
    coverAlt: "Abstract full-stack system connecting interfaces, services, databases, and cloud infrastructure",
    learningOutcomes: ["Responsive React interfaces", "Node.js APIs and authentication", "Relational database design", "Testing and deployment workflows", "A complete capstone product", "A recruiter-ready portfolio"],
    curriculum: [
      { title: "Web foundations", summary: "HTML, CSS, JavaScript, accessibility, and Git.", lessons: ["Semantic interfaces", "Responsive layout systems", "JavaScript fundamentals", "Git collaboration"] },
      { title: "Modern front-end development", summary: "React, TypeScript, state, and data fetching.", lessons: ["Component architecture", "Type-safe application code", "Forms and validation", "API-driven interfaces"] },
      { title: "Back-end systems", summary: "Node.js services, authentication, and API design.", lessons: ["REST API contracts", "Sessions and permissions", "Error handling", "Service testing"] },
      { title: "Data and deployment", summary: "PostgreSQL, migrations, CI, and cloud delivery.", lessons: ["Relational modeling", "Query performance", "Automated checks", "Production deployment"] },
      { title: "Capstone studio", summary: "Plan, build, review, and present a complete product.", lessons: ["Product brief", "Technical design", "Mentor review", "Portfolio presentation"] },
    ],
    requirements: ["No prior coding knowledge required", "A laptop with at least 8 GB RAM", "Comfort using a web browser and files", "Eight to ten study hours each week"],
    materials: ["40+ hours of guided lessons", "Downloadable starter repositories", "Weekly coding exercises", "Six assessed portfolio projects", "Interview and portfolio templates"],
    tools: ["React", "TypeScript", "Node.js", "PostgreSQL", "GitHub", "VS Code"],
    benefits: ["Lifetime lesson access", "Weekly mentor reviews", "Placement preparation", "Resume and portfolio review", "Mock technical interview", "Completion certificate"],
    mentor: { name: "Arjun Menon", role: "Senior Full Stack Engineer", initials: "AM" },
    faqs: buildFaqs("web development", "six months", "a deployed full-stack capstone"),
  },
  {
    slug: "data-science-ai",
    title: "Data Science & AI",
    category: "Data Science",
    eyebrow: "TURN DATA INTO DECISIONS",
    description: "Analyze real datasets, build predictive models, and communicate useful insight.",
    about: "Learn the practical workflow used by data teams: define a question, prepare messy data, explore patterns, build and evaluate models, and present recommendations clearly. Every module ends with evidence you can add to a professional portfolio.",
    duration: "6 months",
    level: "Beginner to intermediate",
    students: "18,420",
    rating: "4.8",
    price: "₹17,999",
    modules: "8 modules",
    projects: "7 projects",
    accent: "from-cyan-500 via-blue-600 to-indigo-800",
    coverImage: "/images/programs/data-science-ai.webp",
    coverAlt: "Data flowing through an analytical model into charts, patterns, and predictions",
    learningOutcomes: ["Python data analysis", "SQL for analytical work", "Statistical reasoning", "Machine-learning workflows", "Decision-ready dashboards", "An end-to-end AI capstone"],
    curriculum: [
      { title: "Python for data work", summary: "Write clear analysis code with Python and notebooks.", lessons: ["Python essentials", "NumPy foundations", "Pandas workflows", "Reproducible notebooks"] },
      { title: "Statistics and exploration", summary: "Use evidence instead of intuition alone.", lessons: ["Descriptive statistics", "Experiment design", "Data visualization", "Insight narratives"] },
      { title: "SQL and data preparation", summary: "Query, join, validate, and reshape datasets.", lessons: ["Analytical SQL", "Data cleaning", "Quality checks", "Feature preparation"] },
      { title: "Machine learning", summary: "Train, compare, and explain predictive models.", lessons: ["Regression", "Classification", "Model evaluation", "Responsible AI"] },
      { title: "Applied AI capstone", summary: "Solve a business problem from brief to presentation.", lessons: ["Problem framing", "Model pipeline", "Dashboard delivery", "Stakeholder presentation"] },
    ],
    requirements: ["No previous data-science experience", "Comfort with basic school mathematics", "A laptop with at least 8 GB RAM", "Eight to ten study hours each week"],
    materials: ["Curated real-world datasets", "Guided notebook exercises", "Seven portfolio projects", "Model evaluation checklists", "Career interview practice"],
    tools: ["Python", "Jupyter", "Pandas", "scikit-learn", "Power BI", "Git"],
    benefits: ["Lifetime lesson access", "Dataset and notebook library", "Mentor project reviews", "Analytics interview practice", "Portfolio storytelling", "Completion certificate"],
    mentor: { name: "Maya Joseph", role: "Lead Data Scientist", initials: "MJ" },
    faqs: buildFaqs("data science", "six months", "a complete predictive analytics case study"),
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    category: "Design",
    eyebrow: "DESIGN WITH EVIDENCE",
    description: "Research user needs and turn them into clear, testable digital experiences.",
    about: "Move through the complete product-design process—from research and information architecture to visual systems, interactive prototypes, and usability testing. You will leave with thoughtful case studies that explain both the outcome and your decisions.",
    duration: "4 months",
    level: "Beginner friendly",
    students: "12,860",
    rating: "4.9",
    price: "₹13,999",
    modules: "7 modules",
    projects: "5 projects",
    accent: "from-emerald-400 via-teal-600 to-cyan-800",
    coverImage: "/images/programs/ui-ux-design.webp",
    coverAlt: "A product design workspace with wireframes, interface components, and user journeys",
    learningOutcomes: ["User interviews and synthesis", "Information architecture", "Wireframes and user flows", "Accessible visual systems", "Interactive prototyping", "Two polished case studies"],
    curriculum: [
      { title: "Design foundations", summary: "Understand users, products, and useful constraints.", lessons: ["UX principles", "Research planning", "Interview practice", "Insight synthesis"] },
      { title: "Structure and interaction", summary: "Turn needs into flows, screens, and prototypes.", lessons: ["Information architecture", "User journeys", "Wireframing", "Interaction patterns"] },
      { title: "Visual systems", summary: "Create interfaces with clear hierarchy and consistency.", lessons: ["Typography", "Color and contrast", "Component systems", "Responsive design"] },
      { title: "Testing and iteration", summary: "Evaluate prototypes and improve with evidence.", lessons: ["Usability studies", "Accessibility review", "Design critique", "Iteration planning"] },
      { title: "Portfolio studio", summary: "Build case studies that communicate your process.", lessons: ["Case-study narrative", "Prototype polish", "Portfolio review", "Presentation practice"] },
    ],
    requirements: ["No previous design experience", "A laptop capable of running Figma", "Curiosity about people and products", "Six to eight study hours each week"],
    materials: ["Research templates", "Reusable Figma libraries", "Five guided product briefs", "Weekly critique sessions", "Portfolio presentation templates"],
    tools: ["Figma", "FigJam", "Maze", "Notion", "Miro", "Adobe CC"],
    benefits: ["Lifetime lesson access", "Weekly design critique", "Portfolio case-study review", "Design interview practice", "Mentor office hours", "Completion certificate"],
    mentor: { name: "Ananya Rao", role: "Principal Product Designer", initials: "AR" },
    faqs: buildFaqs("product design", "four months", "two complete product-design case studies"),
  },
  {
    slug: "cloud-computing",
    title: "Cloud Computing",
    category: "Engineering",
    eyebrow: "SHIP RELIABLE SYSTEMS",
    description: "Deploy, automate, secure, and observe production cloud infrastructure.",
    about: "Build a practical foundation in Linux, networking, cloud architecture, containers, delivery pipelines, and infrastructure as code. Hands-on labs show how modern teams move software from a repository to a reliable production environment.",
    duration: "5 months",
    level: "Beginner to intermediate",
    students: "9,740",
    rating: "4.8",
    price: "₹16,999",
    modules: "8 modules",
    projects: "6 labs",
    accent: "from-orange-400 via-amber-600 to-rose-800",
    coverImage: "/images/programs/cloud-computing.webp",
    coverAlt: "Connected modular cloud infrastructure with secure gateways and deployment paths",
    learningOutcomes: ["Linux and networking basics", "AWS architecture decisions", "Containerized applications", "Automated CI/CD pipelines", "Infrastructure as code", "Monitoring and incident response"],
    curriculum: [
      { title: "Infrastructure foundations", summary: "Linux, networking, identity, and secure access.", lessons: ["Linux operations", "Network fundamentals", "Cloud identity", "Security baselines"] },
      { title: "Cloud architecture", summary: "Design reliable compute, storage, and data services.", lessons: ["AWS core services", "Availability patterns", "Cost awareness", "Architecture reviews"] },
      { title: "Containers and orchestration", summary: "Package and operate consistent workloads.", lessons: ["Docker images", "Container networking", "Kubernetes basics", "Release strategies"] },
      { title: "Automation", summary: "Deliver changes safely with pipelines and infrastructure code.", lessons: ["GitHub Actions", "Terraform", "Secrets management", "Environment promotion"] },
      { title: "Operations capstone", summary: "Deploy and observe a resilient application stack.", lessons: ["Monitoring", "Alerting", "Incident drills", "Reliability review"] },
    ],
    requirements: ["Basic computer and web knowledge", "A laptop with at least 8 GB RAM", "Willingness to use a command line", "Eight study hours each week"],
    materials: ["Cloud lab guides", "Reusable Terraform modules", "Pipeline templates", "Architecture review sheets", "Six assessed infrastructure labs"],
    tools: ["AWS", "Docker", "Kubernetes", "Terraform", "GitHub Actions", "Linux"],
    benefits: ["Lifetime lesson access", "Guided cloud labs", "Architecture mentor reviews", "DevOps interview practice", "Cloud portfolio project", "Completion certificate"],
    mentor: { name: "Nisha Kumar", role: "Cloud Platform Architect", initials: "NK" },
    faqs: buildFaqs("cloud engineering", "five months", "a production-style cloud deployment"),
  },
  {
    slug: "product-management",
    title: "Product Management",
    category: "Business",
    eyebrow: "LEAD FROM INSIGHT",
    description: "Discover valuable problems, align teams, and guide products from idea to impact.",
    about: "Practice the work of a product manager through realistic briefs. You will interview users, frame opportunities, prioritize tradeoffs, write clear requirements, define success metrics, and lead a cross-functional launch simulation.",
    duration: "4 months",
    level: "Beginner friendly",
    students: "8,910",
    rating: "4.8",
    price: "₹14,999",
    modules: "7 modules",
    projects: "5 projects",
    accent: "from-rose-400 via-pink-600 to-orange-700",
    coverImage: "/images/programs/product-management.webp",
    coverAlt: "A product strategy journey connecting customer signals, priorities, and a digital product",
    learningOutcomes: ["Customer discovery", "Opportunity framing", "Roadmap prioritization", "Clear product requirements", "Metrics and experimentation", "Launch and stakeholder leadership"],
    curriculum: [
      { title: "Product thinking", summary: "Understand value, users, markets, and strategy.", lessons: ["Product principles", "Market context", "Business models", "Strategy choices"] },
      { title: "Discovery", summary: "Find and validate problems worth solving.", lessons: ["User interviews", "Insight synthesis", "Opportunity mapping", "Assumption testing"] },
      { title: "Definition and delivery", summary: "Create alignment without prescribing every detail.", lessons: ["Product briefs", "Requirements", "Prioritization", "Team rituals"] },
      { title: "Metrics and growth", summary: "Measure outcomes and learn through experiments.", lessons: ["North-star metrics", "Funnels", "Experiment design", "Decision reviews"] },
      { title: "Launch simulation", summary: "Lead a product from approved brief to market review.", lessons: ["Launch planning", "Stakeholder communication", "Risk management", "Outcome retrospective"] },
    ],
    requirements: ["No previous product role required", "Professional written communication", "Interest in customers and business", "Six to eight study hours each week"],
    materials: ["Product brief templates", "Interview and research scripts", "Prioritization models", "Five realistic product cases", "PM interview question bank"],
    tools: ["Notion", "Jira", "Figma", "Amplitude", "Miro", "Google Sheets"],
    benefits: ["Lifetime lesson access", "Weekly product critique", "PM interview preparation", "Resume positioning", "Portfolio case review", "Completion certificate"],
    mentor: { name: "Rahul Mehta", role: "Group Product Manager", initials: "RM" },
    faqs: buildFaqs("product management", "four months", "a complete product launch case"),
  },
  {
    slug: "generative-ai",
    title: "Generative AI",
    category: "AI / ML",
    eyebrow: "BUILD USEFUL AI SYSTEMS",
    description: "Create grounded AI applications with evaluation, retrieval, and responsible controls.",
    about: "Go beyond prompt demos and learn the engineering workflow behind dependable generative-AI products. You will work with model APIs, retrieval, structured outputs, tool use, evaluation, safety, and deployment through focused application projects.",
    duration: "3 months",
    level: "Intermediate",
    students: "11,560",
    rating: "4.9",
    price: "₹18,999",
    modules: "7 modules",
    projects: "5 projects",
    accent: "from-violet-500 via-indigo-600 to-blue-800",
    coverImage: "/images/programs/generative-ai.webp",
    coverAlt: "A generative AI workflow transforming structured inputs into visual and audio outputs",
    learningOutcomes: ["Effective model prompting", "Structured model outputs", "Retrieval-augmented generation", "Tool-using AI workflows", "Evaluation and guardrails", "A deployed AI application"],
    curriculum: [
      { title: "Model foundations", summary: "Understand capabilities, limits, tokens, and context.", lessons: ["LLM concepts", "Prompt structure", "Structured outputs", "Cost and latency"] },
      { title: "Application patterns", summary: "Create reliable model-powered product flows.", lessons: ["API integration", "Conversation state", "Tool calling", "Error recovery"] },
      { title: "Grounded generation", summary: "Connect models to trusted knowledge.", lessons: ["Embeddings", "Retrieval", "Chunking strategies", "Source attribution"] },
      { title: "Evaluation and safety", summary: "Measure quality and design responsible controls.", lessons: ["Eval datasets", "Quality scoring", "Guardrails", "Human review"] },
      { title: "AI product capstone", summary: "Build and present a production-minded AI application.", lessons: ["Architecture", "Observability", "Deployment", "Product demonstration"] },
    ],
    requirements: ["Comfort with basic Python or JavaScript", "Familiarity with APIs", "A laptop with at least 8 GB RAM", "Eight to ten study hours each week"],
    materials: ["Five application starter kits", "Evaluation templates", "Retrieval datasets", "Architecture examples", "AI engineering interview practice"],
    tools: ["Python", "OpenAI API", "LangChain", "PostgreSQL", "Vector search", "GitHub"],
    benefits: ["Lifetime lesson access", "AI starter repositories", "Weekly engineering reviews", "Evaluation toolkit", "Capstone architecture review", "Completion certificate"],
    mentor: { name: "Kavya Iyer", role: "Applied AI Engineer", initials: "KI" },
    faqs: buildFaqs("generative AI", "three months", "a deployed, evaluated AI application"),
  },
];

export function getMarketingProgram(slug: string): MarketingProgram | undefined {
  return marketingPrograms.find((program) => program.slug === slug);
}

function buildFaqs(subject: string, duration: string, outcome: string) {
  return [
    { question: `Do I need prior ${subject} experience?`, answer: "No specialist experience is required unless noted in the requirements. The opening module establishes the shared foundation used throughout the program." },
    { question: "How is the program delivered?", answer: "You learn through concise lessons, guided practice, live mentor reviews, and projects that mirror real professional work." },
    { question: "How long do I retain access?", answer: `The guided cohort runs for ${duration}, and enrolled learners keep lifetime access to the recorded lessons and core project resources.` },
    { question: "Will I build portfolio work?", answer: `Yes. The program is designed around practical evidence, ending with ${outcome}.` },
    { question: "Is career support included?", answer: "Yes. Career support includes resume positioning, portfolio feedback, interview practice, and guidance on presenting your work." },
  ];
}
