module.exports = {
  DB_CLIENT: 'postgres',
  DB_HOST: process.env.SUPABASE_DB_HOST,
  DB_PORT: 5432,
  DB_DATABASE: 'postgres',
  DB_USER: process.env.SUPABASE_DB_USER,
  DB_PASSWORD: process.env.SUPABASE_DB_PASSWORD,

  PUBLIC_URL: process.env.DIRECTUS_PUBLIC_URL,

  STORAGE_LOCATIONS: 'supabase',
  STORAGE_SUPABASE_DRIVER: 's3',
  STORAGE_SUPABASE_KEY: process.env.SUPABASE_S3_KEY,
  STORAGE_SUPABASE_SECRET: process.env.SUPABASE_S3_SECRET,
  STORAGE_SUPABASE_BUCKET: 'directus',
  STORAGE_SUPABASE_REGION: 'auto',

  CACHE_ENABLED: true,
  CACHE_TTL: '5m',

  RATE_LIMITER_ENABLED: true,
  RATE_LIMITER_POINTS: 100,
  RATE_LIMITER_DURATION: 60,

  EXTENSIONS_PATH: './extensions',
};
