import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "muted-foreground": "var(--muted-foreground)",
        "tertiary-foreground": "var(--tertiary-foreground)",
        surface: "var(--surface)",
        elevated: "var(--elevated)",
        glass: "var(--glass)",
        "glass-border": "var(--glass-border)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        muted: "var(--muted)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        primary: {
          50: "#EBF0FF",
          100: "#D6E0FF",
          200: "#ADC2FF",
          300: "#85A3FF",
          400: "#5C85FF",
          500: "#4F7CFF",
          600: "#3A5FCC",
          700: "#264499",
          800: "#132A66",
          900: "#091533",
        },
        secondary: {
          50: "#F0EDFF",
          100: "#E0DBFF",
          200: "#C2B7FF",
          300: "#A394FF",
          400: "#8570FF",
          500: "#7C5CFF",
          600: "#6349CC",
          700: "#4A3799",
          800: "#312466",
          900: "#191233",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          50: "#E6FDFF",
          100: "#CCFBFF",
          200: "#99F7FF",
          300: "#66F3FF",
          400: "#33EFFF",
          500: "#3DD9FF",
          600: "#00B8D9",
          700: "#008AA6",
          800: "#005C73",
          900: "#002E3A",
        },
      },
      fontFamily: {
        heading: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
        body: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "hero": ["4.5rem", { lineHeight: "1.05", fontWeight: "700" }],
        "hero-xl": ["6rem", { lineHeight: "1.02", fontWeight: "800" }],
      },
      borderRadius: {
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        glow: "0 0 30px var(--color-primary-glow)",
        "glow-sm": "0 0 15px var(--color-primary-glow)",
        glass: "0 8px 32px rgba(0, 0, 0, 0.3)",
      },
      animation: {
        "gradient-shift": "gradient-shift 8s ease infinite",
        "float": "float 6s ease-in-out infinite",
        "float-slow": "float-slow 8s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "shimmer": "shimmer 3s linear infinite",
        "aurora-drift": "aurora-drift 12s ease-in-out infinite",
        "count-up": "count-up 0.6s ease-out forwards",
        "data-sweep": "data-sweep 4s ease-in-out infinite",
        "ambient-float": "ambient-float 20s ease-in-out infinite",
        "pulse-line": "pulse-line 3s ease-in-out infinite",
        "count-in": "count-in 0.6s ease-out forwards",
        "node-pulse": "node-pulse 2s ease-in-out infinite",
      },
      keyframes: {
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "aurora-drift": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(30px, -20px) scale(1.05)" },
          "66%": { transform: "translate(-20px, 10px) scale(0.95)" },
        },
        "count-up": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "data-sweep": {
          "0%": { transform: "translateX(-100%) scaleX(1)", opacity: "0" },
          "20%": { opacity: "1" },
          "80%": { opacity: "1" },
          "100%": { transform: "translateX(200%) scaleX(1.5)", opacity: "0" },
        },
        "ambient-float": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "25%": { transform: "translate(8px, -12px) scale(1.02)" },
          "50%": { transform: "translate(-4px, -20px) scale(0.98)" },
          "75%": { transform: "translate(-12px, -4px) scale(1.01)" },
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
